### ISSUE TITLE
Developer Experience Improvements

### ISSUE THREAD

**Issue by jordanbaron** [LearnWeb3DAO/lw3-cli#13]
What I'm doing

- Adding verbose parameter to functions that need them
### Why?
When creating generators for LW3 projects, things like printing "Begin by typing the following commands to initiate the hardhat project!" aren't needed, because inside of the generator for that project, those commands will be run.

- adding JSDoc comments to all generator functions
- Inside of handlebarsHelpers, check if value argument is of type string before doing anything with it

**Comment by qaderi-coding** [comment]
Man, the installation and generation process are separate actions now.

I made these changes in previous pr and I explained that these two processes are separated from each other.

If remember you reviewed that as well.

I did that according to the following reasons:
1- npx hardhat can't be run programmably it only needs Unix terminal or Windows CMD 
2- to increase the cli reusability, for example someone has installed hardhat or nextjs only wants to generate the files we can say the boilerplates that we would have.
Or just a project that the user wants to generate files only.

**Comment by jordszbordsz** [comment]
It seems we have 2 different visions for this project so I'm just going to let you do what you want to do. I don't see myself continuing this project and I would rather work on things I have a vision for. Revert the PR, I'm unsure as to why you merged it if you didn't agree with the changes.

I wish you the best.

**Comment by qaderi-coding** [comment]
Sure, I just merged I thought you did your tasks.
But, you did changes whatever I made.

Great, do you want to make another repository for your vision?

**Comment by qaderi-coding** [comment]
But, first we should find what is the factor that our visions are different.

**Comment by qaderi-coding** [comment]
If you want to work alone on this project, go with it. I am going to say haardik to remove me from the collobrataion.

This world is full of ideas and opportunities. 
I am going to work on another idea.

We are all here to help people to solve their problems.

Good luck!
